const translations = {
  en: {
    home: "Home",
    courses: "Courses",
    registration: "Registration",
    aboutUs: "About as",
    blog: "Blog",
    contact: "Contact",
    schollInfo: "Discover the endless possibilities of IT",
    month: "month",
    branches: "Branches",
    branchNameArarat: "C. Ararat",
    branchNameErevan: "C .Yerevan",
    whatgiveyou:'What will AIT give you?',
    recomendTitle1:'Education',
    recomendTitle2:'Practice',
    recomendTitle3:'Work',
    recomendTitle1Text:'Take the 10-month course and gain basic programming knowledge. You can also study Graphic Design, UI/UX Design, SMM and English',
    recomendTitle2Text:'After completing the course, take a trial period at a programming company operating under the school. Apply your knowledge by working on real projects.',
    recomendTitle3Text:'Get a chance to join our team. Our students make up 80% of our team.'
  },
  am: {
    home: "Գլխավոր",
    courses: "Դասընթացներ",
    registration: "Գրանցում",
    aboutUs: "Մեր մասին",
    blog: "Բլոգ",
    contact: "Կապ",
    schollInfo: "Բացահայտիր IT անսահման հնարավորությունները",
    month: "ամիս",
    branches: "Մասնաճյուղեր",
    branchNameArarat: "Ք. Արարատ",
    branchNameErevan: "Ք. Երևան",
    whatgiveyou:'Ի՞նչ կտա ձեզ AIT-ն',
    recomendTitle1:'Կրթություն',
    recomendTitle2  :'Պրակտիկա',
    recomendTitle3:'Աշխատանք',
    recomendTitle1Text:'Մասնակցի՛ր 10 ամսյա դասընթացին և ձեռք բեր ծրագրավորման հիմնարար գիտելիքներ: Ինչպես նաև կարող եք ուսանել Graphic Design, UI/UX Design, SMM և Անգլերեն',
    recomendTitle2Text:'Դասընթացի ավարտից հետո անցեք փորձաշրջան դպրոցին կից գործող ծրագրավորման ընկերությունում։ Կիրառի՛ր գիտելիքներդ՝ աշխատելով իրական նախագծերի վրա։',
    recomendTitle3Text:'Ստացի՛ր մեր թիմին միանալու հնարավորություն։ Մեր ուսանողները կազմում են մեր թիմի 80%ը։',
  },
  ru: {
    home: "Основное",
    courses: "Курсы",
    registration: "Регистрация",
    aboutUs: "O нас",
    blog: "Блог",
    contact: "Контакт",
    schollInfo: "Откройте для себя безграничные возможности ИТ",
    month: "месяц",
    branches: "Филиалы",
    branchNameArarat: "Г. Арарат",
    branchNameErevan: "Г .Ереван",
    whatgiveyou:'Что вам даст AIT?',
    recomendTitle1:'Образование',
    recomendTitle2  :'Упражняться',
    recomendTitle3:'Работа',
    recomendTitle2Text:'После прохождения курса пройдите испытательный срок в компании-разработчике, работающей при школе. Применяйте свои знания, работая над реальными проектами.',
    recomendTitle1Text:'Пройдите 10-месячный курс и получите базовые знания в области программирования. Вы также можете изучать графический дизайн, дизайн UI / UX, SMM и английский язык.',
    recomendTitle3Text:'Получите шанс присоединиться к нашей команде. Наши студенты составляют 80% нашей команды.'
  },
};
export default translations;
